### ISSUE TITLE
I keep getting this HTTP_UNAUTHORIZED

### ISSUE THREAD

**Issue by drmed92** [quentinlesceller/zcashd-status#1]
I keep getting this HTTP_UNAUTHORIZED

There has been an error communicating with the Zcash Daemon
HTTP_UNAUTHORIZED
Please report this to test@example.com

my config files match for rpcuser and rpcpassword, all set to admin, and i triple checked it..
still doesn't work, i believe they can communicate, but no authentication..

**Comment by quentinlesceller** [comment]
Hi @drmed92, this fork is unmaintained. So I'm unable to provide any support for it. Closing.

**Comment by drmed92** [comment]
fixed it, 
after checking the config files are correct, run: 
$ dd if=/dev/random bs=32 count=1 2>/dev/null | base64

$ sudo reboot 

then start ./zcashd --daemon **-rpcuser=admin -rpcpassword=password**
